openapi: 3.0.0
info:
  title: Swagger Petstore
  version: 1.0.0
  contact: {}
paths:
  /address/list:
    get:
      summary: ''
      description: ''
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
      operationId: ''
      responses:
        '200':
          description: Description
    post:
      summary: ''
      description: ''
      parameters: []
      operationId: ''
      responses:
        default:
          description: Default response
security: []
servers: []
components:
  links: {}
  callbacks: {}
  schemas: {}
